# Generated by Django 5.2 on 2025-04-05 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ambulance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registration_number", models.CharField(max_length=50, unique=True)),
                ("driver_name", models.CharField(max_length=100)),
                ("contact_number", models.CharField(max_length=15)),
                ("current_latitude", models.FloatField(default=0.0)),
                ("current_longitude", models.FloatField(default=0.0)),
                ("is_available", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Hospital",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("address", models.TextField()),
                ("contact_number", models.CharField(max_length=15)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("emergency_capacity", models.IntegerField(default=10)),
                ("current_occupancy", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "contact_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("address", models.TextField(blank=True, null=True)),
                ("medical_notes", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Emergency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_time", models.DateTimeField(auto_now_add=True)),
                ("pickup_time", models.DateTimeField(blank=True, null=True)),
                ("hospital_arrival_time", models.DateTimeField(blank=True, null=True)),
                ("completion_time", models.DateTimeField(blank=True, null=True)),
                ("patient_latitude", models.FloatField()),
                ("patient_longitude", models.FloatField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("dispatched", "Ambulance Dispatched"),
                            ("picked_up", "Patient Picked Up"),
                            ("en_route_hospital", "En Route to Hospital"),
                            ("arrived_hospital", "Arrived at Hospital"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="requested",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "ambulance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emergencies",
                        to="ambulance_api.ambulance",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emergencies",
                        to="ambulance_api.hospital",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emergencies",
                        to="ambulance_api.patient",
                    ),
                ),
            ],
        ),
    ]
